# Generated by Django 3.0.8 on 2020-07-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('ifsc', models.CharField(max_length=11, primary_key=11, serialize=False)),
                ('branch', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('district', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api1.Banks')),
            ],
            options={
                'db_table': 'branches',
            },
        ),
    ]
